version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  auth:
    build: 
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    image: piotrwrbl/hpds_175856_auth:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - /usr/src/app/node_modules
    command: npm run start:dev auth


  chat:
    build: 
      context: ./
      dockerfile: ./apps/chat/Dockerfile
    image: piotrwrbl/hpds_175856_chat:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - /usr/src/app/node_modules
    command: npm run start:dev chat

  api:
    image: piotrwrbl/hpds_175856_api:latest
    build: 
      context: ./
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - /usr/src/app/node_modules
    command: npm run start:dev api
    

  image:
    build: 
      context: ./
      dockerfile: ./apps/image/Dockerfile
    image: piotrwrbl/hpds_175856_image:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - /usr/src/app/node_modules
    command: npm run start:dev image

  
  angular:
    image: piotrwrbl/hpds_175856_frontend:latest
    build:
      context: ./chatApp
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - '4200:4200'
    volumes:
      - /usr/src/app/node_modules
  
    
    